spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:h2:mem:demodb;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    defer-datasource-initialization: true
    open-in-view: false

server:
  port: 8081
